"""
Django settings for chore_manager project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8vzq5$rsuq6lp+eqw$y0izgw@c1cz^q6!uez=q2*8u1ngkcc3i"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "chores",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "chore_manager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "chore_manager.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Ollama (the chore-assignment agent, chores/agent/runner.py)
# Read from the environment so a different host, model or budget can be tried
# without editing code — local inference setups differ per machine.

OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "http://localhost:11434")

# Measured by the task-8 spike (_docs/model-spike.md): assigns every chore,
# invents no ids, and cuts the effort spread from 9 to 2. It is slow — see the
# timeout below — but it is the only configuration measured that is actually
# fair, so correctness wins over latency here.
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "qwen3:8b")

# Seconds per HTTP call. qwen3:8b was measured at 289s per assignment run on a
# CPU laptop, so 300 left no headroom at all; 600 does. The agent runs inline
# in a request, so this is also the worst case a user waits, and five minutes
# of that is the project's main open problem — see _docs/model-spike.md.
OLLAMA_TIMEOUT = int(os.environ.get("OLLAMA_TIMEOUT", "600"))

# Reasoning models emit a long thinking block before answering. OLLAMA_THINK=0
# turns that off.
#
# Do NOT do that with qwen3:8b. Measured, it is 11x faster and actively wrong:
# the effort spread lands at 10, worse than the 9 you get by assigning nothing,
# and it explains that result just as confidently. For this model the thinking
# block IS the fairness reasoning.
#
# Left unset by default: models that cannot think reject the parameter.
OLLAMA_THINK = {"0": False, "1": True}.get(os.environ.get("OLLAMA_THINK", ""))

# Hard cap on model turns per assignment run, so a model that loops (or keeps
# retrying a bad id) gives up instead of pinning a worker.
OLLAMA_MAX_ITERATIONS = int(os.environ.get("OLLAMA_MAX_ITERATIONS", "12"))
