"""
Django settings for chore_manager project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-8vzq5$rsuq6lp+eqw$y0izgw@c1cz^q6!uez=q2*8u1ngkcc3i"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "chores",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "chore_manager.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "chore_manager.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Ollama (the chore-assignment agent, chores/agent/runner.py)
# Read from the environment so a different host, model or budget can be tried
# without editing code — local inference setups differ per machine.

OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "http://localhost:11434")

# The task-8 spike's leading candidate, NOT yet verified: the spike needs a
# machine with Ollama and has not been run (see _docs/model-spike.md). Treat
# this as a placeholder until that table is filled in.
OLLAMA_MODEL = os.environ.get("OLLAMA_MODEL", "qwen3:8b")

# Seconds per HTTP call. A cold model can spend well over a minute loading
# before it generates a token, and a reasoning model then thinks for a while
# on top of that — 120s turned out to be too tight on real hardware. The agent
# runs inline in a request, so this is also the worst case a user waits per
# model turn.
OLLAMA_TIMEOUT = int(os.environ.get("OLLAMA_TIMEOUT", "300"))

# Reasoning models (qwen3 and friends) emit a long thinking block before
# answering. Set OLLAMA_THINK=0 to turn that off — much faster, at some cost to
# reasoning quality. Left unset by default because models that cannot think
# reject the parameter outright.
OLLAMA_THINK = {"0": False, "1": True}.get(os.environ.get("OLLAMA_THINK", ""))

# Hard cap on model turns per assignment run, so a model that loops (or keeps
# retrying a bad id) gives up instead of pinning a worker.
OLLAMA_MAX_ITERATIONS = int(os.environ.get("OLLAMA_MAX_ITERATIONS", "12"))
